### PR TITLE
Hide `Liked` tweets from stream

### LINKED ISSUE #18: Hide likes from feed
I use a Greasemonkey script to hide likes which appear in your feed as if they were retweets - would be a nice option for this extension.

Implementation here: https://github.com/insin/greasemonkey/blob/master/twitter-hide-retweetlikes.user.js

### PR DESCRIPTION
**Pull request by filipekiss**
Based on @insin's greasemonkey script available here:
https://github.com/insin/greasemonkey/blob/master/twitter-hide-retweetlikes.user.js

Closes #18

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you mention it in the feature highlight in the readme?

https://github.com/sindresorhus/refined-twitter#highlights

**Comment by sindresorhus** [comment]
Would you be interested in joining this project as a maintainer? No worries if not. Just thought I'd ask since you seem interested :)

**Comment by filipekiss** [comment]
@sindresorhus I’d be honored! I’m trying to step-up my JavaScript game and this seemed like a great idea (and your feedback is invaluable!)

**Comment by sindresorhus** [comment]
@filipekiss Awesome. Welcome to the project :)

**Pull request merged**
