### PR TITLE
Change night mode keyboard shortcut to Alt+m

### LINKED ISSUE #64: Keyboard shortcut for night mode mutes tab in Firefox
Hi

PR #62 added a keyboard shortcut for turning on a night mode but in Firefox 58.0.2 (not sure if also not in earlier versions) this shortcut is reserved for muting a tab.

Cheers.

### PR DESCRIPTION
**Pull request by Ricardo-Silva91**
fixes #64 

As @filipekiss suggested, <kbd>Alt</kbd><kbd>m</kbd> doesn't seem to be a native shortcut for the used browsers.

### CODE REVIEW

**Review by filipekiss — APPROVED** [review]

**Comment by sindresorhus** [comment]
Doesn't seem to work on macOS. Nothing happens when I press `Alt+m`.

**Comment by sindresorhus** [comment]
@Ricardo-Silva91 Ping :)

**Comment by Ricardo-Silva91** [comment]
Hello, sorry, I've been kinda busy and forgot this issue.
Turns out on mac the combination `Alt+m` produces the `µ` character, so now the code listens for both the key combination and the character.
I tested and it seems to work 😄.

**Comment by sindresorhus** [comment]
Looks good now. Thanks for your contribution :)

**Pull request merged**
