### PR TITLE
Replace emoji in usernames

### LINKED ISSUE #6: Replace Twitter emoji in usernames too
Currently, we only replace them in tweet bodies.

### PR DESCRIPTION
**Pull request by filipekiss**
I've updated the function that is used for the tweets emoji replacement to also replace them in usernames, either when looking at the stream or when viewing a user profile directly. I'm looking into how to replace them when viewing DMs and I'll update the pull-request later.

@sindresorhus Any reason to restrict emoji replacement with the `#stream-items-id`?

This aims to close #6

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Any reason to restrict emoji replacement with the #stream-items-id?

Not really. You can drop it, and your `.Emoji`.

**Comment by filipekiss** [comment]
Great. I’ll update it. Since we can drop the ID, it’ll probably be easier to make it replace on DMs too.

**Comment by rubenmoya** [comment]
I think dropping `#stream-items-id` will fix https://github.com/sindresorhus/refined-twitter/issues/25 too!

**Comment by filipekiss** [comment]
@rubenmoya Unfortunately, opening the DMs tab doesn't trigger the navigation, so it's not a matter of simply dropping the ID.

@sindresorhus I've updated the code. Let me know if you need anything else changed.

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
