### PR TITLE
Spoof Chrome's User-Agent to fool UA sniffing.

### PR DESCRIPTION
**Pull request by callahad**
A small step toward making this add-on work in Firefox and Edge.

According to @alunny, [this may be unnecessary in the future](https://twitter.com/alunny/status/727594829467680768), so your discretion at merging.

> "there was a CORS + HTTP/2 bug we had to fix and some layout issues. Back on soon!"

As a bonus, `xo` made me confront [Bug 1269863](https://bugzilla.mozilla.org/show_bug.cgi?id=1269863), which we'll hopefully resolve soon.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sure. Easy to remove when it becomes moot. Thanks :)

**Comment by sindresorhus** [comment]
@callahad Do you know of a guide I could link to for Firefox users on how to install this manually?

**Comment by earlcochran** [comment]
I was able to get this running as a temporary add-on in Firefox 48.0a2 with zero changes to the manifest.json.

Just go to about:debugging, click on "Load Temporary Add-on", and open the manifest.json.

The downside to this approach is that on a browser restart, the add-on will be reloaded.

**Comment by callahad** [comment]
We're planning on officially debuting WebExtensions with Firefox 48, which is currently on the Developer Edition channel.

Once Firefox 48 hits Stable, two things need to happen for distribution:

1. Add a unique ID, like `refined-twitter@sindresorhus.github.io`, to the manifest at `applications.gecko.id`.
2. Zip the extension, change its extension to `.xpi`, and [get it signed](https://developer.mozilla.org/en-US/Add-ons/Distribution)

At that point you'll have a .xpi file than any Firefox user can click on to install in their browser.

For now, the "Load Temporary Add-on" button on `about:debugging` on Nightly or DevEdition is the way to go.

**Comment by callahad** [comment]
FWIW, a lot of this can be automated with [the `jpm` tool](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm) as a devDependency.

**Comment by sindresorhus** [comment]
> Add a unique ID, like refined-twitter@sindresorhus.github.io, to the manifest at applications.gecko.id.

According to https://wiki.mozilla.org/WebExtensions/Applications that will not be needed.

**Comment by callahad** [comment]
The plan is to remove that requirement, but I don't think we've implemented automatic ID generation in the signing servers, yet. I'll look into it.

**Comment by alunny** [comment]
The site should be on for Firefox now fyi, so the spoofing can be dropped.

**Comment by arguiot** [comment]
Will it be on Safari?

**Pull request merged**
