### PR TITLE
Fix slow scrolling area repaint

### PR DESCRIPTION
**Pull request by ivancuric**
Promotes two offending elements to their own layers.

image
https://twitter.com/_baxuz/status/939065264410382336

### CODE REVIEW

**Comment by sindresorhus** [comment]
This only improves scroll performance when a single-tweet is modal, right?

**Comment by sindresorhus** [comment]
Can you add something like `- Improves the performance of twitter.com` to https://github.com/sindresorhus/refined-twitter#highlights and make it link to here?

**Comment by ivancuric** [comment]
> This only improves scroll performance when a single-tweet is modal, right?

Yes and no. The `RichEditor-tempTextArea` sometimes remains rendered after you close it as a zero-height fixed position element causing repaints even when the modal is closed. I haven't found the cause, it's probably a state/race condition bug on their end.

> Can you add something like - Improves the performance of twitter.com to sindresorhus/refined-twitter#highlights and make it link to here?

Will do.

**Comment by sindresorhus** [comment]
Awesome! Any other performance improvements more than welcome :D

**Pull request merged**
