### PR TITLE
Hide the big header on profile pages

### PR DESCRIPTION
**Pull request by Miklet**
Hi

This PR corresponds to #55.

I hid the large header on top of the profile page, moved bio lower and tweets higher :)
Changes were really simple.

PS. Sorry for some formatting changes but I had prettier enabled in editor.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> PS. Sorry for some formatting changes but I had prettier enabled in editor.

Can you revert those unrelated changes?

**Comment by sindresorhus** [comment]
After load it seems to push the profile navbar down a bit:

screen shot 2018-02-17 at 04 32 49
screen shot 2018-02-17 at 04 32 51

**Comment by Miklet** [comment]
Oh strange. I will look into it and remove formatting changes.

**Comment by sindresorhus** [comment]
@Miklet Interested in finishing this up? :)

**Comment by Miklet** [comment]
I am sorry but lately I do not have enough time to finish it. If any one would like to pick it up instead I will be totally fine with it.

**Comment by jorgegonzalez** [comment]
Can I try and finish this?

**Pull request closed without merging**
