### PR TITLE
Remove header from profile page

### LINKED ISSUE #55: Remove the header from profiles
As the first step of #5.

The profile headers are totally useless and take up so much vertical space.

### PR DESCRIPTION
**Pull request by jorgegonzalez**
This should finish the work started by @Miklet in #63, and fix #55. The only issue I see is that profile pictures with a white background look kinda weird on the navbar (see AVA screenshot below).

image

image

image

Closes #63

### CODE REVIEW

**Comment by filipekiss** [comment]
I don't dislike the way the AVA profile picture looks, but maybe adding a really subtle shadow to the profile picture would make it less "weird"?

Nice work, btw 👍

**Comment by jorgegonzalez** [comment]
I removed the white border and added a subtle shadow which looks much cleaner, in my opinion.

image
image

**Review by filipekiss — APPROVED** [review]

**Comment by filipekiss** [comment]
I'm good with that!

**Comment by sindresorhus** [comment]
It looks good on the screenshots, but when I try the PR, the profile pics jumps up after load:

screen shot 2018-04-03 at 02 08 55

**Comment by jorgegonzalez** [comment]
@sindresorhus do you maybe have another extension on that is conflicting with this? @filipekiss does it jump up for you as well?

**Comment by sindresorhus** [comment]
I tried running it in Incognito mode with just Refined Twitter and I still see it. Chrome 65.

**Comment by sindresorhus** [comment]
Wonder if my Twitter account somehow have some different Twitter version than you.

**Comment by jorgegonzalez** [comment]
Can you select your profile image in the devtools and share a screenshot? I'd like to see the classes.

**Comment by sindresorhus** [comment]
```html
<div class="ProfileCanopy-avatar">
      <div class="ProfileAvatar">
    <a class="ProfileAvatar-placeholder u-block js-nav js-tooltip profile-picture u-hidden" href="/sindresorhus?edit=true" title="Add a profile photo" data-placement="right" data-scribe-element="profile_avatar">
      <img class="ProfileAvatar-placeholderImage u-bgUserColor" data-avatar-placeholder="true" src="https://abs.twimg.com/a/1522314066/img/t1/highline/empty_state/owner_empty_avatar.png" alt="Sindre Sorhus">
    </a>
    <a class="ProfileAvatar-container u-block js-tooltip profile-picture" href="https://pbs.twimg.com/profile_images/883735352934113280/aDWPvjZ5_400x400.jpg" data-resolved-url-large="https://pbs.twimg.com/profile_images/883735352934113280/aDWPvjZ5_400x400.jpg" data-url="https://pbs.twimg.com/profile_images/883735352934113280/aDWPvjZ5_400x400.jpg" target="_blank" rel="noopener" data-original-title="Sindre Sorhus" loaded="true">
      <img class="ProfileAvatar-image" src="https://pbs.twimg.com/profile_images/883735352934113280/aDWPvjZ5_400x400.jpg" alt="Sindre Sorhus">
    </a>
</div>

        <div class="ProfileAvatarEditing is-withAvatar">
  <div class="ProfileAvatarEditing-placeholder u-bgUserColor"></div>
  <div class="ProfileAvatarEditing-container">
    <img class="ProfileAvatarEditing-image avatar" src="https://pbs.twimg.com/profile_images/883735352934113280/aDWPvjZ5_400x400.jpg" alt="Sindre Sorhus">
  </div>
  <div class="ProfileAvatarEditing-overlay"></div>
  <div class="ProfileAvatarEditing-iframeSaving">
    <div class="ProfileAvatarEditing-iframeSavingHelp">
      <span class="Icon Icon--clock"></span>
      <p>Saving</p>
    </div>
  </div>
  <div class="ProfileAvatarEditing-buttonContainer">
    <button class="ProfileAvatarEditing-button u-boxShadowInsetUserColorHover" type="button" tabindex="2">
      <div class="ProfileAvatarEditing-addAvatarHelp">
        <span class="Icon Icon--cameraPlus"></span>
        <p>Add a profile photo</p>
      </div>
      <div class="ProfileAvatarEditing-changeAvatarHelp">
        <span class="Icon Icon--camera"></span>
        <p>Change your profile photo</p>
      </div>
      <div class="ProfileAvatarEditing-dropAvatarHelp">
        <span class="Icon Icon--cameraPlus"></span>
        <p>Drop profile photo here</p>
      </div>
    </button>
  </div>
    <div id="choose-photo" class="controls avatar-settings inline-upload-avatar dropdown center">
      <div class="uploader-image uploader-avatar clearfix">
        <div class="dropdown-menu">
  <div class="dropdown-caret">
    <span class="caret-outer"></span>
    <span class="caret-inner"></span>
  </div>
  <ul>
    <li id="photo-choose-existing" class="photo-choose-existing upload-photo">
      <button type="button" class="dropdown-link">Upload photo</button>
      <div class="photo-selector">
  <button class="btn" type="button">
      Change photo
    </button>
  <span class="photo-file-name">No file selected</span>
  <div class="image-selector">
    <input type="hidden" name="media_file_name" class="file-name">
    <input type="hidden" name="media_data_empty" class="file-data">
    <label class="t1-label">
      <span class="u-hiddenVisually">Add Photo</span>
      <input type="file" name="media[]" class="file-input js-tooltip" tabindex="-1" title="Add Photo" accept="image/gif,image/jpeg,image/jpg,image/png">
    </label>
  </div>
</div>

    </li>
      <li id="photo-choose-webcam" class="u-hidden">
        <button type="button" class="dropdown-link">Take photo</button>
      </li>
    <li id="photo-delete-image" class="">
      <button type="button" class="dropdown-link">Remove</button>
    </li>
      <li class="dropdown-divider" role="presentation"></li>
      <li class="cancel-options">
        <button type="button" class="dropdown-link">Cancel</button>
      </li>
  </ul>
</div>

      </div>
    </div>
</div>

    </div>
```

**Comment by jorgegonzalez** [comment]
Is there any change if you add `!important` to all the relevant rules in this PR? And I assume this also happens on other users' profiles?

**Comment by filipekiss** [comment]
Yesterday was working fine, today is jumping as well, @jorgegonzalez 

image

Twitter seems to run some kind of script that adds a few styles, so even after the changes are applied some margins are added to a few elements.

**Comment by jorgegonzalez** [comment]
Just reproduced. It seems to happen for me only when the bookmarks bar is toggled off. Chrome 65. I always have it on so I guess that's why I didn't notice earlier.

gif: https://imgur.com/a/L8AtL

Will investigate more soon.

**Comment by jorgegonzalez** [comment]
There is some script injecting styles based on the window height (I think?), and it only happens (for me at least) when the bookmarks bar is disabled.

With this extension off and the bookmarks bar off, after scrolling down a profile page, the navbar changes to include your profile picture, name, and handle as well as the navbar links for that profile:
screen shot 2018-04-03 at 11 35 49 pm

I think this is not being handled well by this extension which is why the styles are conflicting.
 
Will continue to investigate an appropriate solution.

**Comment by jorgegonzalez** [comment]
This should now work with the latest commits. Please test 🙏 @sindresorhus @filipekiss

**Comment by jorgegonzalez** [comment]
image

What I haven't yet done is fix the profile navbar, like in the screenshot, when you scroll down a profile's feed. Would you like this feature as well?

**Comment by jorgegonzalez** [comment]
Also I'd be happy to keep this PR open as a work in progress for a more general "better profile pages" enhancement (#5). Additional suggestions/improvements are welcome.

**Review by filipekiss — APPROVED** [review]
Working like a charm for me!

**Comment by sindresorhus** [comment]
> What I haven't yet done is fix the profile navbar, like in the screenshot, when you scroll down a profile's feed. Would you like this feature as well?

Nah, I find that navbar annoying, so what you have now is much better :)

**Comment by sindresorhus** [comment]
@jorgegonzalez Would you be interested in joining the project as a maintainer? We would love to have you part of the team. No worries if not though. 🦄

**Comment by jorgegonzalez** [comment]
@sindresorhus I’d love to join as a maintainer 😄

**Comment by sindresorhus** [comment]
Awesome! Welcome to the team 🌈🦄

**Comment by jorgegonzalez** [comment]
Happy to be with you 🔥🦄

**Pull request merged**
