### PR TITLE
Improve behavior of escape-key and be smart about users locale.

### PR DESCRIPTION
**Pull request by clentfort**
- Pressing escape will now also close photo views.
- Escape will now look for a button based on the users locale.

I'm new to hacking on chrome extensions so this might be a bit hacky.

### CODE REVIEW

**Comment by paulmolluzzo** [comment]
There are 14 errors on this one. Could you address those before there's a review? Thanks!

**Comment by sindresorhus** [comment]
I realize now targeting the `aria` attribute was too fragile, and I didn't consider different locales. I think we instead should figure out a CSS selector that doesn't use the aria attribute.

**Comment by clentfort** [comment]
For the moment I don't have a better solution than targeting the `aria` attribute. Nevertheless I adjusted my coding-style according to the` .editorconfig`.

**Comment by paulmolluzzo** [comment]
@clentfort when I CMD+F for `_158OzO7l` I only find one button with that class.

**Comment by sindresorhus** [comment]
@paulmolluzzo Can you do a PR with that? I think that's a better solution.

**Comment by paulmolluzzo** [comment]
@sindresorhus can do

**Comment by niksy** [comment]
Is this properly resolved? When I open photo modal I can’t close it with Esc key. Using English locale. Based on the code in master branch, it seems like it’s using class selector which doesn’t exist on the page.

**Pull request closed without merging**
