### PR TITLE
Hide "and others follow" from stream

### LINKED ISSUE #112: Remove "and others follow" from stream
In the same sense of removing the "liked" posts from stream it would be cool to remove these too:

screen shot 2018-05-11 at 21 16 52

### PR DESCRIPTION
**Pull request by elliotsa**
This is really hard to test because I cannot get a tweet like that to show up. It's based on Issue #112  using the idea that these tweets are marked with `data-component-context="suggest_pyle_tweet"`.

Fixes #112

### CODE REVIEW

**Comment by filipekiss** [comment]
Thanks for this PR @elliotsa!

I'll take a look and see if I can test it properly!

**Comment by davisonio** [comment]
Nice one

**Comment by sindresorhus** [comment]
Cannot test this, but the code looks good.

@elliotsa Can you also mention the feature in the "feature highlight" in the readme?

**Comment by elliotsa** [comment]
Done! I wasn't quite sure whether the name was self-explanatory enough so I linked the feature highlight to a screenshot showcasing the tweets in question.

Let me know if that works!

**Comment by sindresorhus** [comment]
@elliotsa That's perfect. Thank you :)

**Pull request merged**
